services:
  demo:
    url: http://localhost:8080

bundles:
  authz:
    service: demo
    resource: /bundles/station1/system.authz/bundle.tar.gz
    polling:
      min_delay_seconds: 1
      max_delay_seconds: 1
  reservations:
    service: demo
    resource: /bundles/station1/reservations.list/bundle.tar.gz
    polling:
      min_delay_seconds: 1
      max_delay_seconds: 1